name: Publish Docker image to pkg.github.com

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push: # debug
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
    env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@master
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set commit tag
      # run: echo "COMMIT_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      run: echo "COMMIT_TAG=v3.9.5" >> $GITHUB_ENV

    - name: Show env, commit ref and and image tag details
      run: |
        env | sort
        echo $COMMIT_TAG
        echo $GITHUB_REF
        echo $GITHUB_SHA

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${COMMIT_TAG}, latest
        build-args: |
          GITHUB_SHA=${GITHUB_SHA}
        cache-from: |
          ${REGISTRY}/${IMAGE_NAME}:latest
