name: Publish Docker image to pkg.github.com

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # push: # debug
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
    env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@master
    
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-github-packages
    - name: Set Docker image name and release tag
      run: echo "DOCKER_TAG=${REGISTRY}/${IMAGE_NAME}:${GITHUB_REF:10}" >> $GITHUB_ENV

    # https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${GITHUB_REF:10}, latest
        build-args: |
          GITHUB_SHA=${GITHUB_SHA}
        cache-from: |
          ${REGISTRY}/${IMAGE_NAME}:latest
